name: wealth_wave
description: Investment portfolio and Wealth management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.19+1
  path_provider: ^2.1.2
  path: ^1.9.0
  intl: ^0.19.0
  provider: ^6.1.1
  primer_progress_bar: ^0.4.1
  pie_chart: ^5.4.0
  toastification: ^1.2.0
  syncfusion_flutter_charts: ^24.1.47+2
  petitparser: ^6.0.2
  http: ^1.2.1
  pair: ^0.1.2
  multi_dropdown: ^2.1.4

dev_dependencies:
  flutter_lints: ^3.0.1
  drift_dev: ^2.15.0
  build_runner: ^2.4.8
  test: ^1.24.9
  mockito: ^5.0.8
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - env