name: wealth_wave
description: Investment portfolio and Wealth management
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  date_utils: ^0.2.0
  logger: ^2.0.2+1
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.14.0
  build_runner: '>2.3.0 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - env
    - assets/
